### ISSUE TITLE
when installling errors out on nvme ssd

### ISSUE THREAD

**Issue by The-Drobe** [ahuacate/proxmox-ubuntu-fileserver#1]
# When installing errors out on nvme SSD
hello
I get the following error when running your script 

<h1>error</h1>

Confirming Proxmox PVE, OS and Boot hard disk ID...
fdisk: cannot open /dev/nvmenp: No such file or directory
environment: line 47: ROOTFS: unbound variable
fdisk: cannot open /dev/[ERROR]: No such file or directory
environment: line 47: ROOTFS: unbound variable
cat: '/sys/block/'$'\033''[m[ERROR]/queue/rotational': No such file or directory
bash: line 525: [: ==: unary operator expected
environment: line 47: ROOTFS: unbound variable
cat: /sys/block/nvmenp/queue/rotational: No such file or directory
bash: line 525: [: ==: unary operator expected
environment: line 47: ROOTFS: unbound variable
cat: /sys/block/nvmenp/queue/rotational: No such file or directory
bash: line 525: [: ==: unary operator expected

fdisk: cannot open /dev/nvmenp: No such file or directory
fdisk: cannot open /dev/nvmenp: No such file or directory
[ERROR] 1@631 Unknown failure occured.
environment: line 47: ROOTFS: unbound variable

<h1>what fdisk -l out puts for nvme ssd</h1>

Device           Start       End   Sectors   Size Type
/dev/nvme0n1p1      34      2047      2014  1007K BIOS boot
/dev/nvme0n1p2    2048   1050623   1048576   512M EFI System
/dev/nvme0n1p3 1050624 250069646 249019023 118.8G Linux LVM

**Comment by ahuacate** [comment]
I am in process of rewriting. By next week hopefully. Sorry about the inconvenience.

**Comment by The-Drobe** [comment]
> I am in process of rewriting. By next week hopefully. Sorry about the inconvenience.

ok thanks for the reply

**Comment by ahuacate** [comment]
Finally fixed I think. Major revamp. Included NVMe so hopefully the bugs gone

**Comment by ahuacate** [comment]
Also added LVM and Basic ext4 for USB storage.
