### ISSUE TITLE
Info on zfs or direct pass

### ISSUE THREAD

**Issue by docop** [ahuacate/proxmox-ubuntu-fileserver#2]
Hi  So your project look quite interesting. Actually, i was not sure about the zfs portion. To get it working, you need to install proxmox with zfs, during the install and kill half of the ram to the zfs.
 Is your script, we can simply deploy, but with a direct passthrough of hdd to vm .. or direct to CT ?

thanks in advance

**Comment by ahuacate** [comment]
There are two currently two available build options. Storage ZFS backend performed by the host. Frontend NAS services (SMB and NFS) performed by a Ubuntu 21.04 CT.
I was not aware  ZFS requires installation when a Proxmox host wasn't built with it. Thanks for the heads up. Will look into that.

**Comment by ahuacate** [comment]
> Hi So your project look quite interesting. Actually, i was not sure about the zfs portion. To get it working, you need to install proxmox with zfs, during the install and kill half of the ram to the zfs. Is your script, we can simply deploy, but with a direct passthrough of hdd to vm .. or direct to CT ?
> 
> thanks in advance

There are currently two available build options. Both use storage provided by a ZFS backend on the host. Frontend NAS services (SMB and NFS) are served by a Ubuntu 21.04 CT. Next is an OMV version using a VM with HBA passthru.
Regarding ZFS issues on non-ZFS PVE install I will follow up. All my PVE hosts are built on ZFS so my oversight. Thanks for the heads up. Will look into that.

**Comment by ahuacate** [comment]
> Hi So your project look quite interesting. Actually, i was not sure about the zfs portion. To get it working, you need to install proxmox with zfs, during the install and kill half of the ram to the zfs. Is your script, we can simply deploy, but with a direct passthrough of hdd to vm .. or direct to CT ?
> 
> thanks in advance
Just noticed bugs with submodules. Will fix. Sorry
